### PR TITLE
update rust for CI

### PR DESCRIPTION
**Pull request by michaelkirk**
I pushed up some new container tags based on: https://github.com/georust/docker-images/pull/7

### CODE REVIEW

**Comment by michaelkirk** [comment]
Whoops. Still pushing actually. 😅

**Comment by michaelkirk** [comment]
bors try

**Comment by michaelkirk** [comment]
Hrmmmm.... I'm getting seemingly new errors. This is based on master, so doesn't incorporate any of the issues from #59...

The failure is while building `--features network geo-types`:

> thread 'proj::test::test_network_enabled_conversion' panicked at 'called `Result::unwrap()` on an `Err` value: Conversion("network error")', src/proj.rs:911:24
33


I think it's maybe because of this? 😬
Screen Shot 2021-01-16 at 10 01 54 PM

I'll try to figure out who that actually is and make sure they know their cert is expired...

**Comment by michaelkirk** [comment]
Reported expired certificate here: https://github.com/OSGeo/PROJ/issues/2504

**Comment by urschrei** [comment]
Apparently all software is broken this weekend. 😭
Bors try

**Comment by urschrei** [comment]
🎉🎉🎉

**Comment by michaelkirk** [comment]
AFAIK this should be good to merge - or were you waiting for something @urschrei?

**Comment by urschrei** [comment]
Oops, sorry!
bors r+

**Pull request merged**
