### PR TITLE
Fix some documentation tests

### PR DESCRIPTION
**Pull request by woshilapin**
Hi, I ran over one typo in one of the test and as I was fixing it, I realize 2 tests were ignored so I decided to propose a fix for it. Hope this helps.

Questions:
- I'm not sure my PR target the correct branch (`master`) please let me know if I need to retarget (and possibly rebase the PR)
- Who should merge the PR? Should it be me or is there a team of official contributors that will take care of it?

### CODE REVIEW

**Comment by woshilapin** [comment]
Any update about who would merge this PR?

**Comment by urschrei** [comment]
Whoops, sorry.

**Comment by woshilapin** [comment]
Haha, no problem. Thanks for the merge.

**Pull request merged**
