### PR TITLE
Update to PROJ 7.2.1

### PR DESCRIPTION
**Pull request by urschrei**
Let's see if this worked…

### CODE REVIEW

**Comment by urschrei** [comment]
bors try

**Comment by urschrei** [comment]
Is 🤖 not working today? Hmph.

**Comment by michaelkirk** [comment]
Probably you're just testing things - but wanted to make sure you didn't accidentally commit the unzipped proj source.

**Comment by urschrei** [comment]
I did winded, but I don't think I did…I think GH unzips them for viewing. Hmm.

**Comment by michaelkirk** [comment]
Hmm... to me it looks like it's in the commit:  `636 files changed, 419990 insertions(+), 11 deletions(-)`

**Comment by urschrei** [comment]
Gremlins.

**Comment by michaelkirk** [comment]
> Gremlins.

Lol, no doubt. Would you mind squashing that commit so that the add and delete don't bloat the repo and diff?

**Comment by urschrei** [comment]
OK done!

**Comment by michaelkirk** [comment]
LGTM!

I'll leave this to you to merge in case you had any magic Docker dance that needed doing.

**Comment by urschrei** [comment]
It should pass tests if (…) I've done the Docker dance right. Let's see.

**Comment by urschrei** [comment]
Ah, bors can't work with this PR because the bot can't interact with PRs that modify workflows: https://forum.bors.tech/t/resource-not-accessible-by-integration/408

I'm gonna move the workflow modification into a separate PR, merge it so the new Docker tag is in use, then rebase and try again. Worst-case scenario is that I discover that something's gone wrong with Docker and master is broken til I either revert the merge or fix it.

**Comment by urschrei** [comment]
bors try

**Comment by urschrei** [comment]
bors try

**Comment by urschrei** [comment]
bors try-

**Comment by urschrei** [comment]
bors try

**Comment by urschrei** [comment]
\o/

bors r+

**Comment by urschrei** [comment]
bors retry

**Comment by urschrei** [comment]
NOW WHAT

**Comment by urschrei** [comment]
bors retry

**Comment by michaelkirk** [comment]
> NOW WHAT
🤣 go easy bors.

re: https://github.com/georust/proj/pull/70/commits/5e06534d378afb137be3867f7fb3873641c43a66

Do you understand that failure? Is it perhaps another flaky test indicative of some platform dependent heisenbug?

**Comment by urschrei** [comment]
I believe it's the same failure we saw on a different (also removed) test that used that Stereo70 string. I inherited it and (as discussed previously) PROJ strings can be finicky beasts, and I am now of the opinion that if I didn't write and validate it myself or get it from a canonical source then it's to be treated with suspicion.
I'd like to replace it, just looking for something suitable rn.

**Pull request merged**
