### PR TITLE
Add feature to configure building with TIFF support.

### PR DESCRIPTION
**Pull request by frewsxcv**
Thoughts? Would be a breaking change since it defaults to not building with TIFF support, and it used to

### CODE REVIEW

**Comment by urschrei** [comment]
I'm fine with it, but I think the network / grid download functionality requires libtiff – if we can't build with tiff support on M1, that's the fundamental problem.

**Comment by urschrei** [comment]
(Also, I'm in a writing hole until mid-next week, so I probably won't be able to _do_ much other than talk about potential fixes)

**Review by michaelkirk — COMMENTED** [review]
> if we can't build with tiff support on M1, that's the fundamental problem.

I think you're right about the fundamental problem.

I think it's still an improvement to make tiff support optional (and probably contingent on the `network` feature). That potentially helps anyone *not* using the network feature and gives *some* way of building on M1.

**Comment by urschrei** [comment]
> I think it's still an improvement to make tiff support optional (and probably contingent on the network feature). That potentially helps anyone not using the network feature and gives some way of building on M1.

You're absolutely correct.

**Review by michaelkirk — APPROVED** [review]
Other than my one suggestion, LGTM!

**Comment by frewsxcv** [comment]
bors r=michaelkirk

**Comment by urschrei** [comment]
\o/

**Pull request merged**
