### PR TITLE
Update to libproj 9.2.1

### PR DESCRIPTION
**Pull request by urschrei**
(Draft for now because we'll have to update CI)

### CODE REVIEW

**Comment by michaelkirk** [comment]
Want me to take a pass at updating CI?

**Comment by urschrei** [comment]
I'm about to open a PR against CI, as it looks like your (delightful) regen script worked. It'd be great if you could have a quick look for sanity and then I can kick off the build / test / publish step, as I now have some more computing power so it might not be massively onerous…

**Comment by urschrei** [comment]
https://github.com/georust/docker-images/pull/24

**Comment by urschrei** [comment]
well, something is definitely Wrong with the new 1.70 image.

**Comment by urschrei** [comment]
If I had to guess, it's because the 1.63 images are based on the image that was present on Docker Hub, and its architecture is `linux/amd64` whereas subsequent images including the 1.70 ones, are `linux/arm64/v8/` (I assume because I built them on an Apple M). Ugh.

**Comment by michaelkirk** [comment]
Ah yes! I hadn’t really thought of it, but I’ve been doing builds on amd64.Want me to kick off a set of builds?On Jul 2, 2023, at 12:24, Stephan Hügel ***@***.***> wrote:﻿
If I had to guess, it's because the 1.63 images are based on the image that was present on Docker Hub, and its architecture is linux/amd64 whereas subsequent images including the 1.70 ones, are linux/arm64/v8/ (I assume because I built them on an Apple M). Ugh.

**Comment by urschrei** [comment]
Yes but no rush! It's Sunday!

**Comment by urschrei** [comment]
I'm confused about this failure.

**Review by michaelkirk — APPROVED** [review]
LGTM

**Comment by urschrei** [comment]
bors r=michaelkirk

**Pull request merged**
