### PR TITLE
enable network test for ci

### PR DESCRIPTION
**Pull request by michaelkirk**
WDYT @urschrei?

### CODE REVIEW

**Comment by urschrei** [comment]
Yes this is a good plan, and further motivation to do something about the CI setup,  ~15 mins per matrix entry is horrible.

**Comment by michaelkirk** [comment]
rebased

**Comment by urschrei** [comment]
Bors retry

**Comment by michaelkirk** [comment]
bors retry

**Comment by michaelkirk** [comment]
😭

**Comment by urschrei** [comment]
Just enabled bors for you @michaelkirk

**Comment by michaelkirk** [comment]
bors retry

**Comment by michaelkirk** [comment]
I completely forgot about this PR. 😅

**Comment by michaelkirk** [comment]
I'm going to pause this for a second to get feedback on #39 since it affects the direction I'd take on this.

**Comment by michaelkirk** [comment]
@urschrei can you take another look? Now that #39 is merged, we have an existing "network" feature flag. To me it seemed reasonable to run the network tests based on that flag, rather than introducing another "run_network_tests" flag. 

WDYT?

I'd be happy to put it back in as a separate flag if you prefer.

**Comment by urschrei** [comment]
This looks good to me!

**Comment by michaelkirk** [comment]
bors r=urschrei

**Pull request merged**
