### PR TITLE
Add a failing test to check that merge queues work (#171) (#173)

### PR DESCRIPTION
**Pull request by michaelkirk**
Hopefully CI won't merge this.

This time I enabled the "require PR" in the branch protection rules.

### CODE REVIEW

**Comment by michaelkirk** [comment]
Clicked "merge when ready" at 13:39 PDT

**Comment by michaelkirk** [comment]
It merged despite the tests failing again.

And now I can't even push up a revert commit:
```
$ git push origin
Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 10 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 415 bytes | 415.00 KiB/s, done.
Total 4 (delta 3), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
remote: Bypassed rule violations for refs/heads/main:
remote: 
remote: - Changes must be made through the merge queue
remote: 
remote: - Changes must be made through a pull request.
remote: 
remote: - Required status check "ci result" is expected.
remote: 
To https://github.com/georust/proj
   91e3579..e97af15  main -> main
```

Github makes me feel dumb. I'm going to disable these checks and push up a revert commit.

**Comment by michaelkirk** [comment]
> now I can't even push up a revert commit:

Correction: it did let me push up the revert commit, it was just noting that I bypassed the rules.

**Comment by urschrei** [comment]
Christ, this thing.

**Pull request merged**
