### PR TITLE
Update proj-sys version

### PR DESCRIPTION
**Pull request by urschrei**
`proj` needs a `proj-sys` with the `bundled_proj_tiff` feature.

### CODE REVIEW

**Comment by urschrei** [comment]
Oh hang on this is going to fail CI – I'll have to bump the version in `proj/Cargo.toml` after this merges.

**Comment by urschrei** [comment]
bors try

**Review by michaelkirk — APPROVED** [review]
LGTM!

**Comment by urschrei** [comment]
bors r=michaelkirk

**Pull request merged**
